name: 提取

on:
  workflow_dispatch:
    inputs:
      boot:
        description: 'boot'
        required: false
        default: false
        type: boolean
      init_boot:
        description: 'init_boot'
        required: false
        default: false
        type: boolean
      rom_url:
        description: 'ROM 下载直链'
        required: true
      baocunname:
        description: '输出名称'
        required: true
        default: ''

jobs:
  extract_partition:
    runs-on: self-hosted
    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 缓存依赖
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 安装依赖
        run: |
          git clone --single-branch --depth=1 https://github.com/sake1227/payload-dumper.git
          cd payload-dumper && pip3 install -r requirement.txt

      - name: 提取镜像
        run: |
          partitions=("")
          [[ "${{ github.event.inputs.boot }}" == "true" ]] && partitions+=("boot")
          [[ "${{ github.event.inputs.init_boot }}" == "true" ]] && partitions+=("init_boot")
          if [ ${#partitions[@]} -eq 0 ]; then 
            echo "请选择至少一个分区类型！"
            exit 1
          fi
          partitions_string=$(IFS=, ; echo "${partitions[*]}")
          python3 ${{ github.workspace }}/payload-dumper/payload_dumper/dumper.py --partitions $partitions_string ${{ github.event.inputs.rom_url }}

      - name: 生成信息
        run: |
          cd ${{ github.workspace }}/output
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> ${{ github.workspace }}/info.md
          echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> ${{ github.workspace }}/info.md
          echo "镜像大小：" >> ${{ github.workspace }}/info.md
          for img_file in *.img; do
            echo "$(du -h "$img_file" | cut -f1) $img_file" >> ${{ github.workspace }}/info.md
          done

      - name: 上传文件
        uses: ncipollo/release-action@v1.14.0
        with:
            artifacts: "${{ github.workspace }}/output/*"
            name: "${{ github.event.inputs.baocunname }}"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
